### ISSUE TITLE
Rename “Submission” to “Script”

### ISSUE THREAD

**Issue by ericfranz** [OSC/frame-renderer#10]
Or if you want to be more specific, MayaScript.

It is a better name than “Submission” which is too close to “Job” and functionally the Submission model works just like a job script.

**Comment by ericfranz** [comment]
“Script” also fits with the other model names “Project” and “Job”. Stick Maya in front of each and you know exactly the domain of each model.

**Comment by johrstrom** [comment]
I was thinking submission should be changed too.  Script sounds a bit esoteric though. How about 'Presets' or 'Settings' or 'JobSettings'.  

I just get the feeling that script is going to sound jargon-y where what where really talking about here is more like settings for a job, and folks readily understand settings.

**Comment by ericfranz** [comment]
Well that model is responsible for the job script template and the template rendering context (which  could also be called job settings as you suggest) and you can call submit on the model to create one or more jobs...

I don’t know if a better name than Script that covers all that. 

As far as in the UI for what the user sees, maybe job settings is okay? Is there some nomenclature in Maya documentation that could be used?

**Comment by johrstrom** [comment]
Ok that's fine, we'll call it 'script' internally and job settings externally. 

I don't know if you can actually save job settings in deadline. Looks like you only define it at submission time?
https://aws.amazon.com/blogs/media/rendering-with-aws-portal-in-thinkbox-deadline/

**Comment by ericfranz** [comment]
FWIW in other apps this model was called “workflow” or “simulation”. In that regard maybe this model is a “Render”?

**Comment by ericfranz** [comment]
Hmm, in the link you shared, I see “workflow”, “configuration”, and “submission” like you have used.

Naming things is hard.

**Comment by ericfranz** [comment]
Maybe RenderConfig? Puppet is considered a type of configuration management which encompasses both scripts and settings so maybe in that regard Config is closer than Settings?

I don’t know. Go with what you think is best. I just wanted to make sure we thought through it a bit.

**Comment by johrstrom** [comment]
This was done in 1c27872b300d28d0056ddc1e6cbab5a764004b9e. internally it's called scripts and users just see items related to "job settings".
