### ISSUE TITLE
Rename scheduled hours to walltime and provide help text for field

### ISSUE THREAD

**Issue by ericfranz** [OSC/frame-renderer#11]
Since the default walltime is 1 hour and we do not know how to set this, it is very likely jobs will exceed the walltime and fail. The output of the job will contain a line like this:

```
=>> PBS: job killed: walltime 3604 exceeded limit 3600
```

Since we provide links to these files to help users debug their problems, using "scheduled hours" instead of walltime actually can cause confusion. It is better to be consistent here.

**Comment by johrstrom** [comment]
Done.
