### ISSUE TITLE
Support multiple nodes

### ISSUE THREAD

**Issue by johrstrom** [OSC/frame-renderer#13]
Initially I had taken out the feature of scheduling on multiple nodes. This was mostly just for testing and getting familiar with qsub and maya.  Initially Maya did not like the []s that get created in the files. 

Here's a snippet of why it didn't work. It couldn't find this tmp file (arg 5) because of the brackets. 
```bash
Arg[4]="-script"
Arg[5]="/tmp/pbstmp.7431620[1]/ASTMPEb83uc.mel"
Arg[6]="-proj"
Arg[7]="/users/PZS0714/johrstrom/maya/projects/2018TestProject"
No match.
// Maya exited with status 1
Time_atEndRender : Wed Jul 31 16:22:08 EDT 2019
RenderDone
```

This ticket is to investigate and ultimately solve scheduling on multipe nodes because that's how the previous version ran so we should have parity with that. Also, clearly, users may actually need that much computing power.

**Comment by johrstrom** [comment]
@ericfranz job arrays won't work without changing our output file strategy.  I think it won't recognize directories with brackets. 

I keep getting jobs to fail with -9 status. From PBS docs it's about not able to open std out streams. I any case, I'd suggest if we do want this (and I imagine we do), we make a timestamped directory to output the files to and store that directory link with the Job model. 

`.../batch_jobs/1567527346/maya.sh.o7795052-1` etc. 

JOB_EXEC_STDOUTFAIL 	-9 	Could not create/open stdout stderr files

```bash
PBS Job Id: 7795043[2].owens-batch.ten.osc.edu
Job Name:   maya-render-2
Exec host:  o0709/0-27+o0687/0-27
Aborted by PBS Server 
Job cannot be executed
See Administrator for help
Exit_status=-9
resources_used.cput=00:00:00
resources_used.vmem=0kb
```

**Comment by ericfranz** [comment]
So it ends up if in -o you specify the output directory but not the filename the default filename is used. So you can do

```
#PBS -o batch_jobs
```

and then you end up with output filenames like:

```
maya.sh.o7795052-1
maya.sh.o7795052-2
maya.sh.o7795052-3
```

so no need there for a timestamped directory. You would want to be careful when adding your own files (i.e. the job script) to suffix appropriately to match the others. ActiveSupport's Inflector class adds a bunch of methods to String useful for this case (parameterize, underscore):

```
irb(main):007:0> "7795441[].owens-batch.ten.osc.edu".parameterize
=> "7795441-owens-batch-ten-osc-edu"
irb(main):008:0> "7795441[].owens-batch.ten.osc.edu".parameterize.underscore
=> "7795441_owens_batch_ten_osc_edu"
```

**Comment by ericfranz** [comment]
Another consideration here, for either job arrays, or multiple nodes, or (utilizing all cores on one node?) is the terms and count of ACCAD's Maya license. For other products, one license may be used per node, or one license used per core, which can hamper parallelization options to the number of available licenses. If the job tries to use more licenses than available it may exit with an error.

**Comment by johrstrom** [comment]
> no need there for a timestamped directory

I only mention the directory for ease of use. Users will find it difficult to group files together when they're trying to debug. Or they'll be sort of overloaded by hundreds of files in a single directory and they have to find 3. 

As to the note about licenses', I'd imagine that it's at least 1 node: 1 license and it could error out which is why it needs to be easy to debug that and find the relevant files.

**Comment by johrstrom** [comment]
This is complete using the directory structure defined above for users' convenience.  You can see the [README](https://github.com/OSC/frame-renderer#finding-the-output-for-multi-node-jobs) on what that looks like.
