### ISSUE TITLE
Cluster choice optimization

### ISSUE THREAD

**Issue by johrstrom** [OSC/frame-renderer#17]
Having several clusters to choose from and not being able to use them is silly and unnecessary, so let's do better. 

What I propose is something like this, 
* you get the list of clusters from the OODAppKit library 
* blacklist however many clusters, in our case `['pitzer','ruby']`
  * document how to override this function like our currently implemented `cluster_ok?`
* In the scripts create/edit view, if there's only 1 cluster in the array, don't even show the dropdown and set the value to one and only setting it can be.

This way we have our cake and eat it too.

**Comment by ericfranz** [comment]
I would set the control as hidden and postpone any modification till we have a requirement to support multiple clusters and thus better idea of what all that would entail.

**Comment by ericfranz** [comment]
Or leave the control as is and do nothing.

**Comment by ericfranz** [comment]
It’s very likely the right solution is not to enable varying the cluster but vary the “Script type” (STI subclass) where a script subclass would include the cluster specific changes including cluster, queue, ppn, batch script changes. But again, easier to decide when requirements are facing us.

**Comment by johrstrom** [comment]
It was fairly easy to just hide it. Also documented how to change it, so folks at other sites can change it.  Also added just a little bit of documentation on how to change the shell script too.
