### ISSUE TITLE
Job Fails To Submit; Accounting ID Not Provided

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/frame-renderer#26]
Although it stored it doesn't look like accounting_id is ever used by the template.

**Comment by MorganRodgers** [comment]
```        Job failed to submit: ["Name #<OodCore::JobAdapterError: ERROR:  Your job has not been submitted to Owens for the following reason:\n\n\tYou have not specified an account and have more than one available.\n\tPlease specify an account.\n\t\n\tAvailable accounts:  PAS1429 PZS0714\n\nPlease review the Owens documentation:\n\n\thttps://www.osc.edu/supercomputing/computing/owens\n\nFeel free to contact oschelp@osc.edu if you have any questions.\n\nqsub: Your job has been administratively rejected by the queueing system.\nqsub: There may be a more detailed explanation prior to this notice.\n>"]```

**Comment by johrstrom** [comment]
I pass it into the oodcore libarary [here in job_opts](https://github.com/OSC/frame-renderer/blob/3d879d901da584c9bced599c9cd8252b9b15fcf7/app/models/script.rb#L122).

But now maybe that presence api is throwing us off.

**Comment by johrstrom** [comment]
OK, I know for sure this works now becuase when I submit for an account PS123 (that's fake, that doesn't exit) I can immediately trigger an error which means we're actually passing account_id correctly. 

I will forever, seemingly, get confused on member variables (@) and Rails attributes.  I was using `@accounting_id` when I should have just used accounting_id and I thought I was being smart by overriding the function accounting_id but alas, another thing that tripped me up.
