### ISSUE TITLE
84 Thumbnails Generated When Frame Range Was 1-10

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/frame-renderer#28]
This may have something to do with the 1-100 job I had stopped short of completion and then deleted before starting another 1-10 run?

**Comment by ericfranz** [comment]
It just generates a thumbnail for each exr in the directory, so that is by design.

**Comment by MorganRodgers** [comment]
That makes sense then. I had erased my thumbnails but not the rendered images.
