### ISSUE TITLE
app crashes if there is no `~/maya/projects` directory

### ISSUE THREAD

**Issue by ericfranz** [OSC/frame-renderer#30]
![screen 2019-09-26 at 3 36 56 PM](https://user-images.githubusercontent.com/512333/65719309-8fcdc980-e073-11e9-93ac-9456e3d15a67.png)

**Comment by ericfranz** [comment]
Since we want to upload and download by default from `~/maya/projects` we should probably have an initializer that uses [mkdir_p](https://ruby-doc.org/stdlib-2.4.1/libdoc/fileutils/rdoc/FileUtils.html#method-c-mkdir_p) or the (I think) `Pathname#mkdir_p`.

Regardless it shouldn't crash if it doesn't exist .

**Comment by johrstrom** [comment]
Agreed, I just used the `FileUtils.mkdir_p` API instead of `Dir.mkdir`. Test and confirmed this works. Even tested how maya reacts to that directory already being there when it boots up, and it's fine.

Releasing 0.1.1 now with this. Also should probably start a CHANGELOG now.
