### ISSUE TITLE
Generate thumbnails using ImageMagick's `convert`

### ISSUE THREAD

**Issue by ericfranz** [OSC/frame-renderer#5]
Possibly do that at compute time while the images are being generated, or at the end of the job if using the maya flag to not rerender frames that have been rendered.

**Comment by ericfranz** [comment]
- Determine if the thumbnails generated using convert will be sufficient for ACCAD even though they are lower quality.
- On the project show page below the submissions table, there would be a display of all the thumbnails for each scene that have been rendered, with links to download the corresponding exr images

**Comment by ericfranz** [comment]
I think do nothing right now. Wait for feedback.

**Comment by ericfranz** [comment]
Remember the only guidance we have currently been given is the purpose of these images is to verify that frames 100-120 aren't completely blank or similarly problematic. For that use case, when you have all the frames in front of you you can scroll and quickly glance to see that they are all "good" or if something is "way off".

Since the only requirements we have from ACCAD I think we can say this satisfies it.

**Comment by MorganRodgers** [comment]
I think chosing the `-auto-gamma` flag is acceptable otherwise the previews may be too dark to see.
