### ISSUE TITLE
Consider using exrtools to create thumbnails

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/frame-renderer#8]
There are CLI tools to convert EXR to PNG. I am not aware of any RPMs that exist, so we would have to build this ourselves.

http://scanline.ca/exrtools/exrtools-0.4.tar.gz

**Comment by johrstrom** [comment]
Sorry @MorganRodgers I'm going to close this, I don't see this as the best option given it's been a long time since it's update and there are other existing tools that we even happen to have on our systems.

**Comment by MorganRodgers** [comment]
Fair enough, but to reiterate why I think that exrtools may be a better solution: when I used ffmpeg to generate pngs from exrs I got a huge difference in the expected lighting. It may not be a problem for previews? Ultimately it'll be up to the users.

**Comment by johrstrom** [comment]
Can you comment on #5 ?  There are flags I can pass in to change brightness, gamma, etc, but I'm not sure what the right move is.

**Comment by ericfranz** [comment]
@MorganRodgers the requirement from ACCAD right now for the thumbnails is not to verify the lighting but whether something more problematic happens, like a set of consecutive frames are just completely blank.

If we get feedback that the fidelity of the thumbnails needs improved, better conversion method like you specified or a viewer that can just open exr directly (https://viewer.openhdr.org/) are options. Of course users can just download an individual frame and open it in their tool of choice as well.
